const secSrvUrl = 'http://100.81.5.26:8094';
const apiUrl = 'http://100.81.5.26:8080';
// 18.234.66.133
export const config = {
  PERMS_LIST_ALL: secSrvUrl + '/security/permissions/listAll',
  PERMS_CREATE: secSrvUrl + '/security/permissions/create',
  PERMS_UPDATE: secSrvUrl + '/security/permissions/update',
  PERMS_GET: secSrvUrl + '/security/permissions/',
  ROLES_LIST_ALL: secSrvUrl + '/security/roles/listAll',
  ROLES_CREATE: secSrvUrl + '/security/roles/create',
  ROLES_UPDATE: secSrvUrl + '/security/roles/update',
  ROLES_GET: secSrvUrl + '/security/roles/',
  USERS_LIST_ALL: secSrvUrl + '/security/users/listAll',
  USERS_CREATE: secSrvUrl + '/security/users/create',
  USERS_UPDATE: secSrvUrl + '/security/users/update',
  USERS_GET: secSrvUrl + '/security/users/',
  UI_MODULES_GET: apiUrl + '/api/cmsmodules',
  EXPORT_USER_PORT: apiUrl + '/api/cmsuserexport',
  CMS_GLOBAL_CONFIG_URL: apiUrl + '/api/cmssettings',
  COLLEGE_URL: apiUrl + '/api/cmscollege',
  PAYMENT_MSG_URL: apiUrl + '/api/cmspayment',

  CMS_SEMESTER_URL: apiUrl + '/api/cmssemesters/',
  CMS_TERM_BY_ACYEAR_URL: apiUrl + '/api/cmsterms-by_academicyearid',
  CMS_DEPARTMENT_URL: apiUrl + '/api/cmsdepartments/',
  CMS_DEPARTMENT_BY_BRANCH_URL: apiUrl + '/api/cmsdepartments-branchid/',
  CMS_BATCH_BY_DEPARTMENT_URL: apiUrl + '/api/cmsbatches-departmentid/',
  CMS_LECTURE_URL: apiUrl + '/api/cmslectures',
  CMS_AM_BY_BATCH_SECTION_URL: apiUrl + '/api/cmsattendance-masters-bybatchsection',
  CMS_AM_BY_DEPARTMENT_URL: apiUrl + '/api/cmsattendance-masters-bydepartmentid',
  CMS_META_LECTURE_URL: apiUrl + '/api/cmsmeta-lecture-selected',
  CMS_META_LECTURE_VIEW_ALL_URL: apiUrl + '/api/cmsmeta-lecture-viewalllectures',
  CMS_HOLIDAY_URL: apiUrl + '/api/cmsholidays/',
  CMS_TERM_URL: apiUrl + '/api/cmsterms/',
  CMS_ACADEMICYEAR_URL: apiUrl + '/api/cmsacademic-years/',
  CMS_HOLIDAY_BY_ACYEAR_URL: apiUrl + '/api/cmsholidays-by_academicyearid',
  CMS_BRANCH_URL: apiUrl + '/api/cmsbranches',
  CMS_BRANCH_BY_COLLEGE_URL: apiUrl + '/api/cmsbranches-collegeid',
  CMS_BATCH_URL: apiUrl + '/api/cmsbatchenums',
  CMS_SECTION_URL: apiUrl + '/api/cmssectionenums',
  CMS_SECTION_BY_BATCH_URL: apiUrl + '/api/cmssections-batchid/',
  CMS_CHECK_USER_SELECTION_URL: apiUrl + '/api/cmscheckuserselection',
  CMS_SUBJECT_URL: apiUrl + '/api/cmssubjects',
  CMS_SUBJECT_BY_DEPARTMENT_URL: apiUrl + '/api/cmssubjects-bydepartmentid',
  CMS_SUBJECT_TEACHER_BY_DEPARTMENT_URL: apiUrl + '/api/cmssubjects-teacher-bydepartmentid',
  CMS_TEACHER_BY_FILTER_PARAM_URL: apiUrl + '/api/cmsteachers-qryprms',
};
